-- Seed Data for Bodhi Learn (Cloudflare D1 & SQLite)

INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('A', 'Apple', '🍎', '#F87171', 'ah', 'A is for Apple. Sweet and crunchy!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('B', 'Ball', '⚽', '#3B82F6', 'buh', 'B is for Ball. Bounce, catch, and play!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('C', 'Cat', '🐱', '#FBBF24', 'kuh', 'C is for Cat. Purr and meow!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('D', 'Dolphin', '🐬', '#38BDF8', 'duh', 'D is for Dolphin. Jumping in waves!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('E', 'Elephant', '🐘', '#818CF8', 'eh', 'E is for Elephant with a long trunk!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('F', 'Frog', '🐸', '#4ADE80', 'fuh', 'F is for Frog. Ribbit, hop hop!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('G', 'Giraffe', '🦒', '#FACC15', 'juh', 'G is for Giraffe reaching the tall trees!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('H', 'Heart', '💖', '#F472B6', 'huh', 'H is for Heart. Full of love and joy!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('I', 'Ice Cream', '🍦', '#F43F5E', 'eye', 'I is for Ice Cream. Yummy and cool!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('J', 'Jellyfish', '🪼', '#A78BFA', 'juh', 'J is for Jellyfish glowing in the ocean!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('K', 'Kangaroo', '🦘', '#EA580C', 'kuh', 'K is for Kangaroo hopping high!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('L', 'Lion', '🦁', '#EAB308', 'luh', 'L is for Lion. King of the jungle!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('M', 'Monkey', '🐵', '#D97706', 'muh', 'M is for Monkey swinging on branches!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('N', 'Nest', '🪺', '#B45309', 'nuh', 'N is for Nest where baby birds sleep!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('O', 'Owl', '🦉', '#9333EA', 'awe', 'O is for Owl. Wise in the night!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('P', 'Penguin', '🐧', '#0284C7', 'puh', 'P is for Penguin waddling on ice!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('Q', 'Queen', '👑', '#C084FC', 'kwuh', 'Q is for Queen wearing a shining crown!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('R', 'Rocket', '🚀', '#EF4444', 'ruh', 'R is for Rocket zooming to the stars!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('S', 'Sun', '☀️', '#F59E0B', 'sss', 'S is for Sun shining warm and bright!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('T', 'Tiger', '🐯', '#F97316', 'tuh', 'T is for Tiger with colorful stripes!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('U', 'Unicorn', '🦄', '#EC4899', 'you', 'U is for Unicorn sparkling with magic!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('V', 'Volcano', '🌋', '#DC2626', 'vuh', 'V is for Volcano tall and mighty!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('W', 'Whale', '🐳', '#0EA5E9', 'wuh', 'W is for Whale singing in the sea!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('X', 'Xylophone', '🎼', '#10B981', 'zyl', 'X is for Xylophone playing musical notes!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('Y', 'Yacht', '⛵', '#06B6D4', 'yuh', 'Y is for Yacht sailing on the water!');
INSERT OR REPLACE INTO alphabet (letter, word, emoji, color, phonics_sound, sentence) VALUES ('Z', 'Zebra', '🦓', '#64748B', 'zzz', 'Z is for Zebra with black and white stripes!');
INSERT OR REPLACE INTO sight_words (id, word, level, hint, emoji, example_sentence) VALUES ('w1', 'SEE', 'pre-k', 'Look with your eyes', '👀', 'I see a happy star!');
INSERT OR REPLACE INTO sight_words (id, word, level, hint, emoji, example_sentence) VALUES ('w2', 'CAN', 'pre-k', 'You are able to do it', '💪', 'You can do anything!');
INSERT OR REPLACE INTO sight_words (id, word, level, hint, emoji, example_sentence) VALUES ('w3', 'BIG', 'pre-k', 'Huge and tall', '🐘', 'That is a big elephant!');
INSERT OR REPLACE INTO sight_words (id, word, level, hint, emoji, example_sentence) VALUES ('w4', 'RED', 'pre-k', 'Color of strawberries', '🍓', 'The apple is bright red.');
INSERT OR REPLACE INTO sight_words (id, word, level, hint, emoji, example_sentence) VALUES ('w5', 'SUN', 'pre-k', 'Shines in the sky', '☀️', 'The warm sun is shining.');
INSERT OR REPLACE INTO sight_words (id, word, level, hint, emoji, example_sentence) VALUES ('w6', 'CAT', 'pre-k', 'A furry friend who purrs', '🐱', 'The cute cat drinks milk.');
INSERT OR REPLACE INTO sight_words (id, word, level, hint, emoji, example_sentence) VALUES ('w7', 'LIKE', 'kindergarten', 'Something you enjoy', '👍', 'I like reading stories.');
INSERT OR REPLACE INTO sight_words (id, word, level, hint, emoji, example_sentence) VALUES ('w8', 'PLAY', 'kindergarten', 'Have fun with friends', '⚽', 'Let us play together outside!');
INSERT OR REPLACE INTO sight_words (id, word, level, hint, emoji, example_sentence) VALUES ('w9', 'STAR', 'kindergarten', 'Twinkling in night sky', '⭐', 'Twinkle, twinkle little star.');
INSERT OR REPLACE INTO sight_words (id, word, level, hint, emoji, example_sentence) VALUES ('w10', 'JUMP', 'kindergarten', 'Hop off both feet', '🦘', 'Watch the bunny jump high!');
INSERT OR REPLACE INTO sight_words (id, word, level, hint, emoji, example_sentence) VALUES ('w11', 'BLUE', 'kindergarten', 'Color of the ocean', '🌊', 'The sky is clear and blue.');
INSERT OR REPLACE INTO sight_words (id, word, level, hint, emoji, example_sentence) VALUES ('w12', 'HELP', 'kindergarten', 'Give a hand to someone', '🤝', 'Friends always help each other.');
INSERT OR REPLACE INTO sight_words (id, word, level, hint, emoji, example_sentence) VALUES ('w13', 'HAPPY', 'grade1', 'Big smile on your face', '😄', 'Today is a happy day!');
INSERT OR REPLACE INTO sight_words (id, word, level, hint, emoji, example_sentence) VALUES ('w14', 'FRIEND', 'grade1', 'Someone you care about', '🧸', 'You are my best friend!');
INSERT OR REPLACE INTO sight_words (id, word, level, hint, emoji, example_sentence) VALUES ('w15', 'ROCKET', 'grade1', 'Flies into outer space', '🚀', 'The rocket flies to the moon!');
INSERT OR REPLACE INTO sight_words (id, word, level, hint, emoji, example_sentence) VALUES ('w16', 'MAGIC', 'grade1', 'Full of wonder and sparkles', '✨', 'The fairy has magic dust!');
INSERT OR REPLACE INTO stories (id, title, cover_emoji) VALUES ('s1', 'Bodhi and the Space Rocket', '🚀');
INSERT INTO story_pages (story_id, page_order, text, image_emoji, bg_color) VALUES ('s1', 0, 'Bodhi looked up at the night sky. The stars were twinkling bright.', '✨', '#1E1B4B');
INSERT INTO story_pages (story_id, page_order, text, image_emoji, bg_color) VALUES ('s1', 1, 'A friendly shiny rocket landed on the grass. "Hop in!" whispered the rocket.', '🚀', '#312E81');
INSERT INTO story_pages (story_id, page_order, text, image_emoji, bg_color) VALUES ('s1', 2, '3, 2, 1... Blast off! They zoomed past the yellow moon and smiling planets.', '🌕', '#0F172A');
INSERT INTO story_pages (story_id, page_order, text, image_emoji, bg_color) VALUES ('s1', 3, 'Bodhi collected three golden stars to take home as a souvenir.', '⭐', '#1E293B');
INSERT INTO story_pages (story_id, page_order, text, image_emoji, bg_color) VALUES ('s1', 4, '"What a wonderful adventure!" Bodhi said with a happy smile.', '🥰', '#3730A3');
INSERT OR REPLACE INTO stories (id, title, cover_emoji) VALUES ('s2', 'The Puppy Who Loved To Count', '🐶');
INSERT INTO story_pages (story_id, page_order, text, image_emoji, bg_color) VALUES ('s2', 0, 'Barnaby the fluffy puppy loved walking in the sunny meadow.', '🐶', '#ECFDF5');
INSERT INTO story_pages (story_id, page_order, text, image_emoji, bg_color) VALUES ('s2', 1, 'He saw 1 busy honey bee buzzing near a sweet daisy.', '🐝', '#FEF3C7');
INSERT INTO story_pages (story_id, page_order, text, image_emoji, bg_color) VALUES ('s2', 2, 'Then he saw 2 playful butterflies dancing in the breeze.', '🦋', '#FEE2E2');
INSERT INTO story_pages (story_id, page_order, text, image_emoji, bg_color) VALUES ('s2', 3, 'Under a big oak tree, he found 3 yummy bones waiting for him!', '🦴', '#E0E7FF');
INSERT INTO story_pages (story_id, page_order, text, image_emoji, bg_color) VALUES ('s2', 4, 'Barnaby wagged his tail happily. Counting with friends was so much fun!', '🐾', '#F3E8FF');
INSERT OR REPLACE INTO reward_stickers (id, name, emoji, cost_stars) VALUES ('st1', 'Super Star', '⭐', 3);
INSERT OR REPLACE INTO reward_stickers (id, name, emoji, cost_stars) VALUES ('st2', 'Rocket Rider', '🚀', 5);
INSERT OR REPLACE INTO reward_stickers (id, name, emoji, cost_stars) VALUES ('st3', 'Dancing Dino', '🦖', 5);
INSERT OR REPLACE INTO reward_stickers (id, name, emoji, cost_stars) VALUES ('st4', 'Magic Unicorn', '🦄', 6);
INSERT OR REPLACE INTO reward_stickers (id, name, emoji, cost_stars) VALUES ('st5', 'Rainbow Joy', '🌈', 4);
INSERT OR REPLACE INTO reward_stickers (id, name, emoji, cost_stars) VALUES ('st6', 'Cool Panda', '🐼', 6);
INSERT OR REPLACE INTO reward_stickers (id, name, emoji, cost_stars) VALUES ('st7', 'Golden Trophy', '🏆', 8);
INSERT OR REPLACE INTO reward_stickers (id, name, emoji, cost_stars) VALUES ('st8', 'Friendly Robot', '🤖', 7);
INSERT OR REPLACE INTO reward_stickers (id, name, emoji, cost_stars) VALUES ('st9', 'Sweet Cupcake', '🧁', 4);
INSERT OR REPLACE INTO reward_stickers (id, name, emoji, cost_stars) VALUES ('st10', 'Space Alien', '👾', 6);
INSERT OR REPLACE INTO reward_stickers (id, name, emoji, cost_stars) VALUES ('st11', 'Crown of Glory', '👑', 8);
INSERT OR REPLACE INTO reward_stickers (id, name, emoji, cost_stars) VALUES ('st12', 'Heart Balloon', '🎈', 4);
INSERT OR REPLACE INTO tracing_words (id, word, emoji, hint) VALUES ('tw1', 'APPLE', '🍎', 'Sweet and crunchy fruit');
INSERT OR REPLACE INTO tracing_words (id, word, emoji, hint) VALUES ('tw2', 'BALL', '⚽', 'Bouncy round toy');
INSERT OR REPLACE INTO tracing_words (id, word, emoji, hint) VALUES ('tw3', 'CAT', '🐱', 'Playful furry friend');
INSERT OR REPLACE INTO tracing_words (id, word, emoji, hint) VALUES ('tw4', 'DOG', '🐶', 'Loyal puppy friend');
INSERT OR REPLACE INTO tracing_words (id, word, emoji, hint) VALUES ('tw5', 'STAR', '⭐', 'Twinkling night light');
INSERT OR REPLACE INTO tracing_words (id, word, emoji, hint) VALUES ('tw6', 'SUN', '☀️', 'Warm and bright');
INSERT OR REPLACE INTO tracing_words (id, word, emoji, hint) VALUES ('tw7', 'MOON', '🌙', 'Glows in the dark sky');
INSERT OR REPLACE INTO tracing_words (id, word, emoji, hint) VALUES ('tw8', 'FISH', '🐟', 'Swims in the clear water');
INSERT OR REPLACE INTO tracing_words (id, word, emoji, hint) VALUES ('tw9', 'BIRD', '🐦', 'Flies high in the sky');
INSERT OR REPLACE INTO tracing_words (id, word, emoji, hint) VALUES ('tw10', 'TREE', '🌳', 'Tall and green');
INSERT OR REPLACE INTO tracing_words (id, word, emoji, hint) VALUES ('tw11', 'CAKE', '🎂', 'Sweet birthday treat');
INSERT OR REPLACE INTO tracing_words (id, word, emoji, hint) VALUES ('tw12', 'BODHI', '🌟', 'Super star learner!');