// Speech engine: plays the pre-recorded Gemini clips in public/audio, and nothing else.
// If a clip is missing or fails to load it stays silent; there is deliberately no fallback to
// the browser's built-in (SpeechSynthesis) voice.
//
// Callers describe *what* to say as a list of clip URLs (see `clip` helpers below)
// instead of free text, so there is no guessing about which recording to play.

export const EXCLAMATIONS = [
  'woohoo', 'yay', 'hurray', 'yippee', 'super',
  'awesome', 'bingo', 'high_five', 'you_rock', 'shining_star',
];

export const RETRY_PHRASES = ['oops_try_again', 'almost_there', 'keep_trying'];

// Studio clips were recorded at a gentle ~0.85x pace, so this "voice speed"
// plays them unchanged. Other speeds scale relative to it.
export const DEFAULT_VOICE_SPEED = 0.85;

// Tiny silent WAV used to unlock the shared <audio> element on iOS.
const SILENT_WAV =
  'data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAAAAA=';

const pick = <T,>(list: T[]): T => list[Math.floor(Math.random() * list.length)];

export const wordKey = (word: string) => word.toUpperCase().replace(/[^A-Z]/g, '');

// Narration clips (generated by scripts/audio/generate.mjs from scripts/audio/manifest.mjs)
const AUDIO_BASE = '/audio';

// Clip paths are relative to AUDIO_BASE
export const clip = {
  // Whole sentences per letter ("Can you find the letter K?"): a lone letter name, or a sentence
  // fragment stitched onto one, is what voice models get wrong most often
  findLetter: (letter: string) => `letters/find_${letter.toUpperCase()}.mp3`,
  traceLetter: (letter: string) => `letters/trace_${letter.toUpperCase()}.mp3`,
  phonics: (letter: string) => `letters/phonics_${letter.toUpperCase()}.mp3`,
  number: (n: number) => `numbers/${n}.mp3`,
  word: (word: string) => `words/${wordKey(word)}.mp3`,
  spelling: (word: string) => `words/spelling_${wordKey(word)}.mp3`,
  phrase: (id: string) => `phrases/${id}.mp3`,
  math: (id: string) => `math/${id}.mp3`,
  sentence: (id: string) => `sentences/${id}.mp3`,
  storyPage: (storyId: string, pageIndex: number) => `stories/${storyId}_p${pageIndex}.mp3`,
  storyTitle: (storyId: string) => `stories/${storyId}_title.mp3`,
  readAlong: (sentenceId: string) => `readalong/${sentenceId}.mp3`,
  cheer: () => `exclamations/${pick(EXCLAMATIONS)}.mp3`,
  retry: () => `phrases/${pick(RETRY_PHRASES)}.mp3`,
};

interface SayOptions {
  // Called once everything has been said (or immediately if voice is off).
  // Never called if the speech is interrupted by another say()/stop().
  onEnd?: () => void;
}

class KidSpeechEngine {
  public speechRate = DEFAULT_VOICE_SPEED;
  public speechEnabled = true;
  public muted = false;

  private audio: HTMLAudioElement | null = null;
  private generation = 0;
  private attempt = 0;
  private unlocked = false;

  constructor() {
    if (typeof window === 'undefined') return;
    // Unlock audio on the very first touch so later programmatic playback works on iOS
    const unlock = () => this.unlock();
    window.addEventListener('pointerdown', unlock, { once: true, capture: true });
  }

  private get canSpeak() {
    return this.speechEnabled && !this.muted && typeof window !== 'undefined';
  }

  private get playbackRate() {
    return Math.min(1.3, Math.max(0.7, this.speechRate / DEFAULT_VOICE_SPEED));
  }

  private getAudio() {
    if (!this.audio) {
      this.audio = new Audio();
      this.audio.preload = 'auto';
    }
    return this.audio;
  }

  private unlock() {
    if (this.unlocked) return;
    this.unlocked = true;
    const audio = this.getAudio();
    if (!audio.paused) return;
    audio.src = SILENT_WAV;
    audio.play().catch(() => {});
  }

  // Say a sequence of clips back to back. Interrupts anything currently playing.
  public say(clips: string[], { onEnd }: SayOptions = {}) {
    const gen = this.interrupt();
    const finish = () => {
      if (gen === this.generation) onEnd?.();
    };

    if (!this.canSpeak) {
      queueMicrotask(finish);
      return;
    }

    const playAt = (i: number) => {
      if (gen !== this.generation) return;
      if (i >= clips.length) {
        finish();
        return;
      }
      // A clip that fails to load is skipped: silence, never another voice
      this.playClip(clips[i], gen, () => playAt(i + 1), () => playAt(i + 1));
    };
    playAt(0);
  }

  public stop() {
    this.interrupt();
  }

  private interrupt() {
    this.generation += 1;
    if (this.audio && !this.audio.paused) {
      this.audio.pause();
    }
    return this.generation;
  }

  private playClip(path: string, gen: number, onDone: () => void, onFail: () => void) {
    this.playUrl(`${AUDIO_BASE}/${path}`, gen, onDone, onFail);
  }

  private playUrl(url: string, gen: number, onDone: () => void, onFail: () => void) {
    const audio = this.getAudio();
    // A failed load fires both `error` and a rejected play(); act on the first
    // outcome only, and only while this is still the element's current attempt
    const attempt = ++this.attempt;
    const settle = (fn: () => void) => () => {
      if (gen !== this.generation || attempt !== this.attempt) return;
      this.attempt++;
      fn();
    };
    audio.onended = settle(onDone);
    audio.onerror = settle(onFail);
    audio.src = url;
    // Setting src resets the rate in some browsers, so apply it afterwards
    audio.defaultPlaybackRate = this.playbackRate;
    audio.playbackRate = this.playbackRate;
    audio.preservesPitch = true;
    audio.play().catch((err: DOMException) => {
      // AbortError just means a newer src replaced this one
      if (err.name === 'AbortError') return;
      // Autoplay blocked: skip silently rather than falling back to another blocked voice
      settle(err.name === 'NotAllowedError' ? onDone : onFail)();
    });
  }
}

export const speech = new KidSpeechEngine();
